### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by fulldecent** [mmehdig/20q#1]
Do you have any seeding data to share?

**Comment by mmehdig** [comment]
Unfortunately not. for 4 reasons:
1. the idea behind this type of question answering is very naive and usually users win.
2. users participation is only one word: yes/no
3. the project was developed for a course project when I was master student and after that I didn't have any hosting server for it. So, any data generated by participants were on my laptop.
4. it was using freebase api by google back then, I don't think it is active now. this data is freely available as a public domain data (I think)

**Comment by fulldecent** [comment]
Got it, thank you for clarifying!

**Comment by fulldecent** [comment]
Oh, P.S. here is a similar project and this is why I was asking: https://github.com/fulldecent/19-questions

**Comment by mmehdig** [comment]
Thank you for the link.
